name: Build
on: { push: null, pull_request: null }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - { uses: pnpm/action-setup@v2, with: { version: 8 } }
    - { uses: actions/setup-node@v3, with: { node-version: ">=16", cache: pnpm } }
    - run: pnpm install
    - run: pnpm package
